### ISSUE TITLE
Why react as dependency?

### ISSUE THREAD

**Issue by krzysiek1507** [jhorowitz-firedrum/redux-ui#2]
Hi! Why did you move react to dependencies from dev- and peerDependencies?

**Comment by ghost** [comment]
Because it is a runtime dependency.

https://github.com/AoD-Technologies/react-redux-ui-tools/blob/0e1efd0a43223d656deaa084eb89ae4d3d04c96c/src/ui.js#L3

**Comment by krzysiek1507** [comment]
@jhorowitz-firedrum all of react packages have react as a runtime dependency but they have it in `peerDependencies` to not include a different version of react to your bundle.
https://github.com/erikras/redux-form/blob/master/package.json
https://github.com/wojtekmaj/react-calendar/blob/master/package.json
https://github.com/reactjs/react-redux/blob/master/package.json

[Article](https://nodejs.org/en/blog/npm/peer-dependencies/) about it.
